### ISSUE TITLE
It seems there is no libvrender.so in lib directory

### ISSUE THREAD

**Issue by lfkabc** [zidootech/zidoo-kodi-14.2#1]
Good job！

It seems there is no libvrender.so in lib directory??

Another question : this apk is just run on X1 product or all H3 chip?

**Comment by zidootech** [comment]
run on all H3 chip
about libvrender.so,We will check it

**Comment by zidootech** [comment]
I added the so file a moment ago.
Sorry for that.

**Comment by lfkabc** [comment]
:+1:   Thank you so much for your reply.

**Comment by lfkabc** [comment]
I get errors while compile this project, the information is something like 

'system/players/dvdplayer/libdvdnav-arm.so: open: No such file or directory'


It seams there is no system/players folder and subdirectories.
